# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5173cbfece266429a1ad156ed7e7d4ef5b3b988fbbbf4e42903bdf21c3593efee36302ddcfc23a0f4553d92a6a972183b534f0ca4c287944801a74146fe3fa8f

test:
  secret_key_base: 6feddf5b1cce3364bf63e9b5e9e5681137cd7ba8b332090c64ee61667a9cb92111f266d409c11561bfb1a6a7b3f3d6615ab70fe76ee253970c084459a3c65e36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
